Figure_Theme <- theme_bw()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())+
  theme(plot.title=element_text(size=8))+
  theme(axis.text.x = element_text(angle=0, hjust=0.5))+
  theme(axis.text.x = element_text(colour="black", size=8))+
  theme(axis.text.y = element_text(colour="black", size=8))+
  theme(axis.title=element_text(size=8))+
  theme(axis.ticks=element_line(colour="black",size=0.5))+
  theme(axis.line=element_line(colour="black")) + 
  theme(legend.title=element_text(size=8))+
  theme(legend.text=element_text(size=8))+
  theme(axis.line=element_blank()) + 
  theme(panel.border = element_rect(fill=NA, size=1))

# Raw file: generated by Fig3b-2.py
BranchCombination_UMI_MutCount <- read.table('BranchCombination_UMI_MutCount_Three.txt', header = TRUE)
head(BranchCombination_UMI_MutCount)

UMI_MutCount_Density <- ggplot(BranchCombination_UMI_MutCount, 
                               aes(x = mut_count, group = num)) + 
  geom_density(data = BranchCombination_UMI_MutCount[BranchCombination_UMI_MutCount$Group == 'Parental',],
               colour = 'grey', alpha = 0.1, linewidth = 0.1) + 
  geom_density(data = BranchCombination_UMI_MutCount[BranchCombination_UMI_MutCount$Group == 'Offspring',],
               colour = 'red', alpha = 1) + 
  scale_x_continuous(breaks = seq(0, 200, by = 10)) + 
  facet_wrap(~Branch, scale = 'free') +
  Figure_Theme
UMI_MutCount_Density
