Figure_Theme <- theme_bw()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())+
  theme(plot.title=element_text(size=8))+
  theme(axis.text.x = element_text(angle=0, hjust=0.5))+
  theme(axis.text.x = element_text(colour="black", size=8))+
  theme(axis.text.y = element_text(colour="black", size=8))+
  theme(axis.title=element_text(size=8))+
  theme(axis.ticks=element_line(colour="black",size=0.5))+
  theme(axis.line=element_line(colour="black")) + 
  theme(legend.title=element_text(size=8))+
  theme(legend.text=element_text(size=8))+
  theme(axis.line=element_blank()) + 
  theme(panel.border = element_rect(fill=NA, size=1))

# File generated by Fig3b-1.py
BranchCombination_Mut <- read.table('BranchCombination_RandomSampling.txt', header = TRUE)
head(BranchCombination_Mut)
unique(BranchCombination_Mut$Branch)

BranchCombination_hist <- ggplot(BranchCombination_Mut, 
                                 aes(x = Mut_InDiffBranch_Count)) + 
  geom_histogram(data = BranchCombination_Mut[BranchCombination_Mut$Group == 'Random',],
                 bins = 25, colour = '#212529', fill = '#0096c7') + 
  geom_point(data = BranchCombination_Mut[BranchCombination_Mut$Group == 'Observation',],
             aes(x = Mut_InDiffBranch_Count, y = 30), color = "red", size = 1) + 
  xlab('mut_count') + 
  scale_x_continuous(limits = c(40,70), breaks = seq(0, 500, by = 5)) + 
  scale_y_continuous(breaks = seq(0, 1000, by = 50)) + 
  facet_wrap(~Branch, scale = 'free_y') + 
  Figure_Theme
BranchCombination_hist
