Figure_Theme <- theme_bw()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())+
  theme(plot.title=element_text(size=8))+
  theme(axis.text.x = element_text(angle=0, hjust=0.5))+
  theme(axis.text.x = element_text(colour="black", size=8))+
  theme(axis.text.y = element_text(colour="black", size=8))+
  theme(axis.title=element_text(size=8))+
  theme(axis.ticks=element_line(colour="black",size=0.5))+
  theme(axis.line=element_line(colour="black")) + 
  theme(legend.title=element_text(size=8))+
  theme(legend.text=element_text(size=8))+
  theme(axis.line=element_blank()) + 
  theme(panel.border = element_rect(fill=NA, size=1))

# File generated by Fig3d.py
FreqMut_Linkage <- read.table('Example-379CT_439CT_630CT_981CT.txt', header = TRUE)
FreqMut_Linkage <- FreqMut_Linkage[,c('sample','mut_info','mut_freq')]
head(FreqMut_Linkage)

# Leaf position information.
plant1_Leaves_pos <- read.table('plant1_Sample_Position.txt', header = TRUE)
plant1_Leaves_pos$Branch <- substr(plant1_Leaves_pos$sample,1,2)

plant1_Leaves_pos$group <- ifelse(grepl('P', plant1_Leaves_pos$sample), 'Offspring','Leaves')

FreqMut_Linkage <- merge(FreqMut_Linkage,plant1_Leaves_pos,by = 'sample',all.y = TRUE)
FreqMut_Linkage[is.na(FreqMut_Linkage)] <- 0
  
Mut_Pos_point <- ggplot(FreqMut_Linkage, aes(x = x, y = y)) + 
    geom_point(data = FreqMut_Linkage[FreqMut_Linkage$Branch == 'RL',],
               aes(color = mut_freq, shape = group), size = 5) + 
    scale_colour_gradient(low = "#adb5bd", high = "black",limits = c(0, 0.1),
                          oob = scales::censor, na.value = "black") +
    new_scale_color() +
    geom_point(data = FreqMut_Linkage[FreqMut_Linkage$Branch == 'B1',],
               aes(color = mut_freq, shape = group), size = 5) + 
    scale_colour_gradient(low = "#caf0f8", high = "#03045e",limits = c(0, 0.1),
                          oob = scales::censor, na.value = "#03045e") +
    new_scale_color() +
    geom_point(data = FreqMut_Linkage[FreqMut_Linkage$Branch == 'B2',],
               aes(color = mut_freq, shape = group), size = 5) + 
    scale_colour_gradient(low = "#e0aaff", high = "#240046",limits = c(0, 0.1),
                          oob = scales::censor, na.value = "#240046") +
    new_scale_color() +
    geom_point(data = FreqMut_Linkage[FreqMut_Linkage$Branch == 'B3',],
               aes(color = mut_freq, shape = group), size = 5) + 
    scale_colour_gradient(low = "#b7e4c7", high = "#1b4332",limits = c(0, 0.1),
                          oob = scales::censor, na.value = "#1b4332") +
    geom_text(aes(label = sample), vjust = -1.5, size = 3) + 
  Figure_Theme
Mut_Pos_point
