Figure_Theme <- theme_bw()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())+
  theme(plot.title=element_text(size=8))+
  theme(axis.text.x = element_text(angle=0, hjust=0.5))+
  theme(axis.text.x = element_text(colour="black", size=8))+
  theme(axis.text.y = element_text(colour="black", size=8))+
  theme(axis.title=element_text(size=8))+
  theme(axis.ticks=element_line(colour="black",size=0.5))+
  theme(axis.line=element_line(colour="black")) + 
  theme(legend.title=element_text(size=8))+
  theme(legend.text=element_text(size=8))+
  theme(axis.line=element_blank()) + 
  theme(panel.border = element_rect(fill=NA, size=1))

# Generated by Step5 in:
# Pipeline-of-lineage-tracing-in-Arabidopsis/Analysis-pipelines/Call-somatic-and-germline-mutation/Mutation-for-UMIC-seq/Filter-bona-fide-mutations/

Parental_mutation <- read.table(paste0(path,"ConsensusSequence_CallSNP_Raw.txt"), header = T)
head(Parental_mutation)

RawMutFreq_hist <- ggplot(Parental_mutation, aes(x = log10(freq))) +
  geom_histogram(bins = 100, fill = "lightblue", color = "darkgrey") +
  geom_vline(xintercept = log10(0.6), color = "red", linetype = "dashed", size = 0.5) +
  scale_x_continuous(breaks = seq(-10, 0, by = 1)) +
  Figure_Theme
